# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# new lines, 06-28-2017
cowsay 'The fundamentals is the jam!'
alias jam='echo fundamentals'
